CREATE TABLE users
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name            VARCHAR(255),
    last_name             VARCHAR(255),
    gender                VARCHAR(50),
    age                   BIGINT,
    date_of_birth         date,
    martal_status         VARCHAR(30),
    email                 VARCHAR(100),
    phone_number          VARCHAR(15),
    password              VARCHAR(255),
    nationality           VARCHAR(100),
    identification_type   VARCHAR(50),
    identification_number VARCHAR(255),
    identity_attachment   VARCHAR(255),
    status                VARCHAR(50),
    otp                   VARCHAR(20),
    created_at            TIMESTAMP WITHOUT TIME ZONE,
    updated_at            TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_users PRIMARY KEY (id)
);